import type { Metadata } from "next";
import Navbar from "@/components/marketing/Navbar";
import Footer from "@/components/marketing/Footer";

export const metadata: Metadata = { title: "Terms of Service — LIMINALsva" };

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="min-h-screen" style={{ background: "linear-gradient(180deg, #f9f5ef 0%, #ffffff 100%)" }}>
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-24">

          <h1 className="font-serif text-4xl text-certify-deep mb-2">Terms of Service</h1>
          <p className="text-sm text-certify-cool-grey mb-12">
            LIMINALsva Platform, a service of KLM Design Studio, Inc.
          </p>

          <div className="prose-legal">

            <p className="text-xs text-certify-cool-grey uppercase font-bold tracking-widest mb-8">
              PLEASE READ THESE TERMS OF SERVICE ("AGREEMENT" OR "TERMS") CAREFULLY AND IN THEIR ENTIRETY BEFORE ACCESSING OR USING THE LIMINAL PLATFORM, A SERVICE OF KLM DESIGN STUDIO, INC. ("PLATFORM," "SITE," OR "SERVICE"). THIS AGREEMENT CONSTITUTES A LEGALLY BINDING CONTRACT BETWEEN YOU ("USER," "CUSTOMER," OR "YOU") AND LIMINAL, A SERVICE OF KLM DESIGN STUDIO, INC AND ITS OWNERS, MEMBERS, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, LICENSORS, SUCCESSORS, AND ASSIGNS (COLLECTIVELY, "COMPANY," "WE," "US," OR "OUR").
            </p>
            <p className="text-xs text-certify-cool-grey uppercase font-bold tracking-widest mb-8">
              BY ACCESSING THE PLATFORM, CREATING AN ACCOUNT, PURCHASING CREDITS, UPLOADING ANY DOCUMENTS, OR USING ANY FEATURE OF THE SERVICE IN ANY MANNER WHATSOEVER, YOU UNCONDITIONALLY AGREE TO BE BOUND BY THESE TERMS IN THEIR ENTIRETY. IF YOU DO NOT AGREE TO EVERY PROVISION OF THESE TERMS, YOU MUST IMMEDIATELY CEASE ALL USE OF THE PLATFORM AND MAY NOT ACCESS OR USE THE SERVICE UNDER ANY CIRCUMSTANCES.
            </p>
            <p className="text-xs text-certify-cool-grey uppercase font-bold tracking-widest mb-12">
              YOUR CONTINUED USE OF THE PLATFORM CONSTITUTES YOUR ONGOING, AFFIRMATIVE, AND UNCONDITIONAL ACCEPTANCE OF THESE TERMS AS THEY MAY BE MODIFIED FROM TIME TO TIME.
            </p>

            <Section number="1" title="DESCRIPTION OF SERVICE">
              <Subsection number="1.1" title="Nature of Service">
                The Platform provides an AI-assisted document analysis and generation service designed to support project teams, architects, engineers, sustainability consultants, building owners, and other professionals ("Project Teams") who are pursuing certification programs (collectively, "Certification Programs"). The Service uses artificial intelligence technology, including technology provided by third-party AI providers, to analyze documents submitted by Users and generate output documents ("Output Documents") that may assist in the preparation of certification submissions.
              </Subsection>
              <Subsection number="1.2" title="Supporting Role Only">
                <Caps>The Service is provided solely as a support tool. The Company does not provide certification consulting services, professional engineering services, architectural services, legal services, or any other licensed professional services. The Platform is not a substitute for qualified professional judgment and is not intended to be used as such.</Caps>
              </Subsection>
              <Subsection number="1.3" title="No Guarantee of Certification Acceptance">
                <Caps>The Company makes absolutely no representation, warranty, guarantee, or promise of any kind, express or implied, that any Output Documents generated by the Platform will be accepted, approved, or recognized by the U.S. Green Building Council (USGBC), the Green Business Certification Inc. (GBCI), the International WELL Building Institute (IWBI), any certifying body, any governmental authority, any reviewer, or any other third party, in whole or in part, under any circumstances.</Caps>
                <p className="mt-3">The quality, completeness, and acceptability of Output Documents generated by the Platform is entirely and exclusively dependent upon the quality, completeness, accuracy, and sufficiency of the information, data, and documents provided by the User. The Company has no control over and assumes no responsibility whatsoever for the ultimate determination of any Certification Program reviewer or certifying body. Users expressly acknowledge and agree that certification outcomes are governed by factors entirely outside the Company's control, including but not limited to: changes in Certification Program standards, reviewer discretion, submission formatting requirements, project-specific conditions, regulatory requirements, and the inherent limitations of AI-assisted analysis.</p>
              </Subsection>
              <Subsection number="1.4" title="Credit-Based Purchase Model">
                Access to the Service requires the purchase of service credits ("Credits"). Each use of the Service's document analysis and generation function requires one or more Credits, as specified prior to purchase. Credits are non-refundable, non-transferable, and have no cash value. The Company reserves the right to modify Credit pricing, Credit requirements, and the features available for a given number of Credits at any time without notice.
              </Subsection>
            </Section>

            <Section number="2" title="ELIGIBILITY AND ACCOUNT REGISTRATION">
              <Subsection number="2.1" title="Eligibility">
                You must be at least eighteen (18) years of age and have the legal capacity to enter into binding contracts in your jurisdiction to use the Service. By using the Service, you represent and warrant that you meet these requirements. You further represent that you are using the Service for lawful purposes only and in connection with legitimate building certification activities.
              </Subsection>
              <Subsection number="2.2" title="Account Responsibility">
                You are solely responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify the Company immediately of any unauthorized use of your account. The Company shall not be liable for any loss, damage, or harm arising from your failure to maintain the security of your account.
              </Subsection>
              <Subsection number="2.3" title="Accurate Information">
                You represent and warrant that all information you provide to the Company, including during registration and in connection with any document upload, is accurate, complete, and current. You accept full and sole responsibility for all consequences arising from inaccurate, incomplete, misleading, or outdated information.
              </Subsection>
            </Section>

            <Section number="3" title="DOCUMENT SUBMISSION AND HANDLING">
              <Subsection number="3.1" title="Required Documents">
                Prior to initiating a Service transaction, the Platform will inform Users of the categories of documents required to perform the requested analysis. Users are solely responsible for identifying, gathering, and submitting all required documents. The Company's identification of required document categories is provided as general guidance only and does not constitute a guarantee that the identified documents will be sufficient for any particular Certification Program submission.
              </Subsection>
              <Subsection number="3.2" title="User Responsibility for Submitted Documents">
                <Caps>You are solely and exclusively responsible for all documents submitted to the Platform. By submitting documents, you represent and warrant that:</Caps>
                <ul className="mt-3 space-y-2 text-sm text-certify-cool-grey leading-relaxed">
                  <li>You have the legal right to submit such documents and to grant the Company the right to process them as contemplated by these Terms;</li>
                  <li>The documents are accurate, complete, authentic, and not fraudulent, falsified, or materially misleading in any respect;</li>
                  <li>The submission and processing of such documents does not violate any applicable law, regulation, contractual obligation, intellectual property right, privacy right, or other right of any third party;</li>
                  <li>You have obtained all necessary consents, authorizations, and permissions from any third parties whose information, intellectual property, or personal data may be contained in the submitted documents;</li>
                  <li>The documents do not contain any malware, viruses, corrupted data, or code designed to interfere with or damage the Platform or any systems.</li>
                </ul>
              </Subsection>
              <Subsection number="3.3" title="Document Retention and Deletion">
                The Company will retain User-submitted documents only for the period necessary to complete the requested analysis and generate Output Documents. Upon completion of the analysis, all User-submitted documents will be permanently and irrevocably deleted from the Company's systems. The Company does not guarantee any specific deletion timeline and shall not be liable for any delay in deletion. Output Documents generated by the Platform may be retained for a reasonable period to allow User download. Users are solely responsible for downloading and retaining Output Documents they wish to preserve.
              </Subsection>
              <Subsection number="3.4" title="Document Quality">
                The Company's AI systems will attempt to assess the quality and completeness of submitted documents and notify Users of apparent deficiencies. However, such assessment is not guaranteed to be accurate or comprehensive. The Company makes no warranty that its quality assessment will identify all deficiencies, errors, or omissions. The Company shall bear no responsibility for Output Documents that are inadequate, incomplete, or inaccurate as a result of deficiencies in User-submitted documents, whether or not such deficiencies were identified by the Platform's quality assessment.
              </Subsection>
            </Section>

            <Section number="4" title="OUTPUT DOCUMENTS AND LIMITATIONS">
              <Subsection number="4.1" title="Nature of Output Documents">
                Output Documents are generated by artificial intelligence systems based solely upon the documents, data, and information submitted by the User. Output Documents are provided "as-is" without any warranty of any kind. Output Documents are intended to serve as draft materials or reference materials to support a User's own professional review and certification submission process. Output Documents are not final, certified, stamped, or professionally reviewed documents.
              </Subsection>
              <Subsection number="4.2" title="User's Obligation to Review">
                <Caps>Users are solely responsible for reviewing, verifying, correcting, and validating all Output Documents prior to any use, submission, reliance, or distribution. The Company expressly disclaims all responsibility for any Output Document that is used without adequate professional review. Users should engage qualified professionals, including LEED Accredited Professionals, WELL Accredited Professionals, or other certified consultants, to review all Output Documents before submission to any certifying body.</Caps>
              </Subsection>
              <Subsection number="4.3" title="Certification Outcomes">
                <Caps>The Company does not guarantee, represent, or warrant that: (A) any Output Document will meet the requirements of any Certification Program; (B) any Output Document will be accepted by any certifying body; (C) any project will achieve LEED, WELL, or any other certification as a result of using the Service; (D) the analysis performed by the Platform is consistent with the current version of any Certification Program standard; or (E) the use of the Service will reduce the time, cost, or effort required to achieve certification. Certification Program requirements change frequently and the Company makes no warranty that the Platform is updated to reflect current requirements.</Caps>
              </Subsection>
              <Subsection number="4.4" title="Third-Party AI Limitations">
                The Platform uses third-party artificial intelligence services to perform analysis and generate Output Documents. AI systems are inherently probabilistic and may produce inaccurate, incomplete, inconsistent, or inappropriate outputs. The Output Document quality is dictated by the quality of information provided by Users. The Company does not warrant the accuracy, reliability, or fitness of any AI-generated content. Users acknowledge the inherent limitations of AI technology and assume all risks associated with reliance on AI-generated outputs. The Company provides these services as part of what is needed to submit for certification and expects Users to review and edit the outputs prior to submittal to meet their certification needs.
              </Subsection>
            </Section>

            <Section number="5" title="FEES, CREDITS, AND PAYMENT">
              <Subsection number="5.1" title="Fees">
                Use of the Service requires payment of applicable fees through the purchase of Credits. All fees are stated in United States Dollars unless otherwise specified. All fees are due in advance of service use. The Company reserves the right to change its fee structure at any time. Updated fees will apply to new Credit purchases following notice of the change.
              </Subsection>
              <Subsection number="5.2" title="No Refunds">
                <Caps>All Credit purchases are final and non-refundable under all circumstances.</Caps> The Company will not issue refunds or credits for unused Credits, Credits used in connection with outputs the User is dissatisfied with, Credits expended in connection with analyses that fail to produce acceptable certification documents, or for any other reason whatsoever. The Company's obligation is limited to the provision of the Service in the manner described herein, and satisfaction with the Output Documents is expressly not a condition of payment.
              </Subsection>
              <Subsection number="5.3" title="Taxes">
                Users are solely responsible for all taxes, levies, or duties imposed by taxing authorities in connection with their purchase or use of Credits or the Service. The Company may collect taxes where required by applicable law.
              </Subsection>
            </Section>

            <Section number="6" title="DISCLAIMER OF WARRANTIES">
              <p className="text-sm text-certify-cool-grey leading-relaxed mb-4">
                To the maximum extent permitted by applicable law, the Platform, the Service, and all Output Documents are provided "as is," "as available," and "with all faults," without warranty of any kind, either express or implied, statutory, or otherwise. The Company, on behalf of itself and its owners, members, managers, officers, directors, employees, agents, successors, and assigns, hereby expressly disclaims all warranties, including but not limited to:
              </p>
              <ul className="space-y-2 text-sm text-certify-cool-grey leading-relaxed mb-4">
                <li>Any implied warranty of merchantability, fitness for a particular purpose, title, or non-infringement;</li>
                <li>Any warranty that the Service will be uninterrupted, error-free, secure, or free from viruses or other harmful components;</li>
                <li>Any warranty regarding the accuracy, completeness, reliability, timeliness, or quality of any Output Documents or analysis;</li>
                <li>Any warranty that Output Documents will satisfy the requirements of any Certification Program, certifying body, or regulatory authority;</li>
                <li>Any warranty that the Service will meet the User's specific requirements or expectations;</li>
                <li>Any warranty arising from course of dealing, course of performance, or usage of trade.</li>
              </ul>
              <p className="text-sm text-certify-cool-grey leading-relaxed">
                No oral or written information or advice given by the Company or its representatives shall create a warranty. Some jurisdictions do not allow the exclusion of implied warranties; in such jurisdictions, the foregoing exclusions apply to the fullest extent permitted by applicable law.
              </p>
            </Section>

            <Section number="7" title="LIMITATION OF LIABILITY AND INDEMNIFICATION">
              <Subsection number="7.1" title="Limitation of Liability">
                <p className="text-sm text-certify-cool-grey leading-relaxed mb-3">To the maximum extent permitted by applicable law, under no circumstances whatsoever shall the Company, or any of its owners, members, managers, officers, directors, employees, contractors, agents, licensors, successors, or assigns (collectively, the "Company Parties") be liable to you or to any third party for any:</p>
                <ul className="space-y-2 text-sm text-certify-cool-grey leading-relaxed mb-4">
                  <li>Direct, indirect, incidental, consequential, special, exemplary, punitive, or any other damages of any kind;</li>
                  <li>Loss of profits, revenue, data, business opportunities, goodwill, or anticipated savings;</li>
                  <li>Costs of procurement of substitute services;</li>
                  <li>Certification denial, delay, or revocation;</li>
                  <li>Fines, penalties, or sanctions imposed by any authority;</li>
                  <li>Third-party claims arising from your use of Output Documents;</li>
                  <li>Loss, corruption, or unauthorized access to submitted documents;</li>
                  <li>Any other loss or damage, whether based in contract, tort (including negligence), strict liability, statute, or any other legal or equitable theory, even if the Company has been advised of the possibility of such damages.</li>
                </ul>
                <p className="text-sm text-certify-cool-grey leading-relaxed">The Company Parties' total cumulative liability to you for all claims arising out of or related to these Terms or the Service, regardless of the form of the action, shall not exceed the lesser of (A) the total amount of Credits purchased by you in the three (3) months immediately preceding the event giving rise to the claim, or (B) one hundred United States dollars ($100.00). This limitation is a fundamental element of the basis of the bargain between you and the Company and applies even if this remedy is found to have failed of its essential purpose.</p>
              </Subsection>
              <Subsection number="7.2" title="User Indemnification">
                You shall defend, indemnify, and hold harmless the Company Parties from and against any and all claims, demands, suits, proceedings, losses, liabilities, damages, costs, and expenses (including reasonable attorneys' fees) arising out of or relating to: (a) your use of the Service or any Output Documents; (b) your submission of documents to the Platform, including any claim that submitted documents infringe any third-party right; (c) your violation of these Terms; (d) your violation of any applicable law or regulation; (e) your negligence, willful misconduct, or fraud; (f) any claim by any certifying body, client, government authority, or third party arising from your use of Output Documents; or (g) any inaccuracy, insufficiency, or misrepresentation in documents submitted to the Platform.
              </Subsection>
              <Subsection number="7.3" title="Essential Bargain">
                You expressly acknowledge that the limitations of liability and disclaimers of warranty set forth in these Terms are a fundamental element of the basis of the bargain between you and the Company, and that the Company would not provide the Service in the absence of such limitations. The Service is offered at the prices set forth herein in reliance on these limitations.
              </Subsection>
            </Section>

            <Section number="8" title="INTELLECTUAL PROPERTY">
              <Subsection number="8.1" title="Platform Ownership">
                The Platform, including all software, algorithms, interfaces, branding, design, documentation, and underlying technology, is owned exclusively by the Company or its licensors and is protected by intellectual property laws. You are granted a limited, non-exclusive, non-transferable, revocable license to access and use the Platform solely in accordance with these Terms. No other license is granted.
              </Subsection>
              <Subsection number="8.2" title="Output Documents">
                Subject to your compliance with these Terms and payment of applicable fees, the Company grants you a limited license to use Output Documents solely in connection with your own building certification submission activities. You may not resell, sublicense, or distribute Output Documents as a standalone product or service.
              </Subsection>
              <Subsection number="8.3" title="Submitted Documents">
                You retain ownership of documents you submit to the Platform. You grant the Company a limited, non-exclusive license to process, analyze, and use submitted documents solely to provide the Service. This license terminates upon deletion of submitted documents as provided in Section 3.3.
              </Subsection>
              <Subsection number="8.4" title="Feedback">
                If you provide any feedback, suggestions, or ideas regarding the Service ("Feedback"), you hereby assign to the Company all rights in such Feedback and agree that the Company may use and disclose Feedback for any purpose without any restriction or compensation to you.
              </Subsection>
            </Section>

            <Section number="9" title="PROHIBITED CONDUCT">
              <p className="text-sm text-certify-cool-grey leading-relaxed mb-3">You agree that you will not:</p>
              <ul className="space-y-2 text-sm text-certify-cool-grey leading-relaxed">
                <li>Use the Service for any unlawful purpose or in violation of any applicable law or regulation;</li>
                <li>Submit fraudulent, falsified, forged, or materially misleading documents to the Platform;</li>
                <li>Attempt to reverse-engineer, decompile, disassemble, or otherwise discover the source code or underlying AI models of the Platform;</li>
                <li>Use automated means to access the Platform or scrape data from the Platform;</li>
                <li>Interfere with or disrupt the integrity or performance of the Platform;</li>
                <li>Attempt to gain unauthorized access to any portion of the Platform or its related systems;</li>
                <li>Use the Service to generate documents for projects with which you have no legitimate involvement or authorization;</li>
                <li>Misrepresent your identity, credentials, or professional role to the Company;</li>
                <li>Sell, resell, or transfer Credits or access to the Platform to any third party without express written consent of the Company;</li>
                <li>Use the Service in any manner that could damage, disable, overburden, or impair the Platform or servers.</li>
              </ul>
            </Section>

            <Section number="10" title="MODIFICATIONS TO TERMS AND SERVICE">
              The Company reserves the right to modify these Terms at any time and in its sole discretion. Changes will be effective upon posting to the Platform or upon notification by any other reasonable means. Your continued use of the Service following any modification constitutes your unconditional acceptance of the revised Terms. You are responsible for reviewing these Terms periodically. The Company also reserves the right to modify, suspend, discontinue, or terminate the Service or any feature thereof at any time without notice and without liability to you.
            </Section>

            <Section number="11" title="TERMINATION">
              The Company may suspend or terminate your access to the Service at any time, for any reason or no reason, with or without notice, and without liability. Upon termination, all of your licenses under these Terms will immediately cease. Provisions of these Terms that by their nature should survive termination shall survive, including without limitation Sections 4, 6, 7, 8, 11, and 12.
            </Section>

            <Section number="12" title="GOVERNING LAW, DISPUTE RESOLUTION, AND WAIVER OF JURY TRIAL">
              <Subsection number="12.1" title="Governing Law">
                These Terms shall be governed by and construed in accordance with the laws of the State of California, United States of America, without regard to its conflict of laws principles. You consent to the exclusive jurisdiction and venue of the state and federal courts located in San Diego, CA for all disputes not subject to arbitration.
              </Subsection>
              <Subsection number="12.2" title="Mandatory Arbitration">
                <Caps>Any dispute, claim, or controversy arising out of or relating to these Terms or the Service shall be resolved exclusively by binding arbitration administered by the American Arbitration Association under its Commercial Arbitration Rules, except that either party may seek injunctive or other equitable relief in a court of competent jurisdiction to prevent irreparable harm. The arbitration shall be conducted by a single arbitrator and shall take place in San Diego, CA.</Caps>
              </Subsection>
              <Subsection number="12.3" title="Class Action Waiver">
                <Caps>You waive any right to bring any dispute as a class, consolidated, representative, or private attorney general action, or to participate in a class, consolidated, representative, or private attorney general action brought by anyone else. The arbitrator shall have no authority to combine or aggregate claims, conduct a class arbitration, or award relief to a group of claimants in one proceeding.</Caps>
              </Subsection>
              <Subsection number="12.4" title="Waiver of Jury Trial">
                <Caps>You expressly waive your right to a trial by jury for any dispute arising out of or related to these Terms or the Service.</Caps>
              </Subsection>
              <Subsection number="12.5" title="Statute of Limitations">
                Any claim you have against the Company must be filed within one (1) year after the claim arises or such claim is permanently and irrevocably barred. This limitations period applies regardless of any statute of limitations that would otherwise be applicable.
              </Subsection>
            </Section>

            <Section number="13" title="MISCELLANEOUS">
              <Subsection number="13.1" title="Entire Agreement">
                These Terms constitute the entire agreement between you and the Company with respect to the subject matter hereof and supersede all prior and contemporaneous understandings, agreements, representations, and warranties.
              </Subsection>
              <Subsection number="13.2" title="Severability">
                If any provision of these Terms is found invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect. The invalid provision shall be modified to the minimum extent necessary to make it valid and enforceable.
              </Subsection>
              <Subsection number="13.3" title="No Waiver">
                The Company's failure to enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.
              </Subsection>
              <Subsection number="13.4" title="Assignment">
                You may not assign or transfer these Terms or any of your rights or obligations hereunder without the prior written consent of the Company. The Company may freely assign these Terms without restriction. These Terms are binding upon and inure to the benefit of the parties and their permitted successors and assigns.
              </Subsection>
              <Subsection number="13.5" title="Force Majeure">
                The Company shall not be liable for any failure or delay in performance resulting from causes beyond its reasonable control, including without limitation acts of God, natural disasters, pandemics, governmental actions, failures of third-party service providers, or telecommunications failures.
              </Subsection>
              <Subsection number="13.6" title="Contact">
                Questions regarding these Terms may be directed to:{" "}
                <a href="mailto:info@liminalsva.com" className="text-certify-blue hover:text-certify-teal transition-colors">
                  info@liminalsva.com
                </a>
              </Subsection>
            </Section>

          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}

function Section({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return (
    <div className="mb-10">
      <h2 className="font-serif text-xl text-certify-deep mb-4 pb-2 border-b border-certify-white">
        {number}. {title}
      </h2>
      <div className="space-y-4">{children}</div>
    </div>
  );
}

function Subsection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="text-sm font-bold text-certify-deep mb-2">{number} {title}</h3>
      <div className="text-sm text-certify-cool-grey leading-relaxed">{children}</div>
    </div>
  );
}

function Caps({ children }: { children: React.ReactNode }) {
  return (
    <p className="text-sm text-certify-cool-grey leading-relaxed font-medium">
      {children}
    </p>
  );
}
